### ISSUE TITLE
Vertical text alignment off

### ISSUE THREAD

**Issue by RichardD2** [madskristensen/DocumentMargin#5]
This may seem like a minor issue, but the text added by this extension is not vertically aligned with the other text in the same bar.

![image](https://github.com/madskristensen/DocumentMargin/assets/2158265/cf802d5c-8930-45fc-9b99-2fa9910ef6b5)

After adding the line, you can see that "Ln: 1", "Ch: 1", "TABS", and "CRLF" are all a few pixels lower than the new "sel", "length", "lines", and "encoding" items.

Perhaps this is a high-DPI issue? I have a 4k monitor (3840x2160) scaled to 175%.

---

Microsoft Visual Studio Professional 2022 Version 17.8.4
VisualStudio.17.Release/17.8.4+34408.163

Editor Info   1.0.30

Windows 11 Version 10.0.22631

**Comment by madskristensen** [comment]
This is fixed in the latest version, which removes the **Length** and **Lines** controls, and introducing an icon in the corner that shows that information on hover

**Comment by RichardD2** [comment]
Thanks for that. It's better, but the encoding item is still not quite right:

![image](https://github.com/madskristensen/DocumentMargin/assets/2158265/2d332cb7-55d2-408d-aefe-de96f36b1b8b)

For example, you can see that the "B" in "TABS" is slightly lower than the "B" in "BOM".

**Comment by HamRusTal** [comment]
@madskristensen Thanks for the great extension (and tons of other ones)!

Unfortunately, the issue resurfaced in a much more pronounced form. (In case it matters, in VS 2022 17.14.34.)

If [another extension](https://marketplace.visualstudio.com/items?itemName=wmj.Codist) inserts a margin widget that slightly increases the bar height, it becomes glaringly obvious that the Selection and Encoding widgets are aligned to the top rather than to the baseline:
<img width="1757" height="49" alt="Image" src="https://github.com/user-attachments/assets/e8945843-26b4-4b6a-b83d-a7b2891eb29d" />

**P.S.** As un unrelated side note, the ⓘ icon on the right reads very poorly in light themes due to extremely low contrast.

**Comment by HamRusTal** [comment]
@RichardD2 Do you have enough permissions to reopen the issue based on my findings?

**Comment by RichardD2** [comment]
@HamRusTal No; you may need to open a new issue instead.
